### PR TITLE
Add note on Travis not supporting sudo-enabled Linux

### PR DESCRIPTION
**Pull request by nicoleepp**
Add documentation in relation to #70

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Review by omus — APPROVED** [review]

**Comment by nicoleepp** [comment]
Windows appveyor builds seem to intermittently fail with `Failed to Connect` errors:

```julia
 Error During Test at C:\projects\ftpclient-jl\test\ftp_object.jl:84
  Got exception FTPClientError("Failed to connect.", 0x00000038) outside of a @test
  Failed to connect. :: LibCURL error #56
  Stacktrace:
   [1] ftp_perform(::ConnContext, ::Bool) at C:\projects\ftpclient-jl\src\FTPC.jl:227
   [2] #ftp_command#12(::Bool, ::Function, ::ConnContext, ::String) at C:\projects\ftpclient-jl\src\FTPC.jl:575
```

**Comment by omus** [comment]
@nicoleepp probably worth opening an issue about. Your changes are good to merge though.

**Comment by nicoleepp** [comment]
I don't have merge permissions on this repo :)

**Comment by nicoleepp** [comment]
https://github.com/invenia/FTPClient.jl/issues/72

**Comment by omus** [comment]
> I don't have merge permissions on this repo :)

Time to get that fixed

**Comment by omus** [comment]
@nicoleepp you should be able to merge now.

**Pull request merged**
