### PR TITLE
Enabling windows 64 appveyor builds

### PR DESCRIPTION
**Pull request by samuel-massinon**

### CODE REVIEW

**Comment by omus** [comment]
Not currently working on 0.5

**Comment by samuel-massinon** [comment]
There was a fix recently for the issue I was having so I though I would test it. The latest build does not include it yet though.

**Comment by omus** [comment]
Gotcha. Keep me posted

**Comment by omus** [comment]
Fixed via https://github.com/JuliaLang/julia/issues/15455

**Comment by omus** [comment]
@samuel-massinon-invenia we're good to merge?

**Comment by samuel-massinon** [comment]
@omus Yup

**Pull request merged**
